[project]
name = "taxifare-mlops-intro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sebastianstohrer", email = "basti.stohrer@hotmail.de" }
]
requires-python = ">=3.12.9"
dependencies = []

[project.scripts]
taxifare-mlops-intro = "taxifare_mlops_intro:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
